### ISSUE TITLE
Change bootstrap theme

### ISSUE THREAD

**Issue by re1naldo** [cniska/yiistrap#113]
I have been looking Twitter Bootstrap themes in Wrapbootstrap and I wonder if those themes are compatible with Yiistrap or not. Will it require a lot of work to use those themes with Yiistrap? Or can we just overwrite files in 'assets' folder?

**Comment by hdushku** [comment]
Setup
Download the latest release from Yii extensions by following the link below:

http://www.yiiframework.com/extension/bootstrap/

yii-bootstrap-2.1.0.r355.zip

Unzip the extension under protected/extensions/bootstrap and modify your application configuration accordingly:
If you wish to use the provided Bootstrap theme copy the theme directory to your themes directory.
And rename the theme to boostrap: okokok
// Define a path alias for the Bootstrap extension as it's used internally.
// In this example we assume that you unzipped the extension under protected/extensions.
Yii::setPathOfAlias('bootstrap', dirname(__FILE__).'/../extensions/bootstrap');
 
return array(
    'theme'=>'bootstrap', // requires you to copy the theme under your themes directory
    'modules'=>array(
        'gii'=>array(
            'generatorPaths'=>array(
                'bootstrap.gii',
            ),
        ),
    ),
    'components'=>array(
        'bootstrap'=>array(
            'class'=>'bootstrap.components.Bootstrap',
        ),
    ),
);
You're done! Now you can start using Bootstrap in your application. For examples on how to use the widgets please visit the docs.

**Comment by crisu83** [comment]
@hdushku you are mixing yiistrap with my old yii-bootstrap extension.

@realtebo & @nek-v: add the theme stylesheet in your web under css and register it through ```CClientScript``` in your layout like so:

```php
<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . "/css/theme.css") ?>
```

Sorry for the long delay in answering, I must have overlooked this issue.
