### ISSUE TITLE
include(TbArray.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by andrewjameshough** [cniska/yiistrap#193]
This is the error you receive when trying to use the TbHtml helper anywhere in your application. There's a line at the top of TbHtml.php that is missing:

Yii::import('bootstrap.helpers.TbArray');

Without this the TbArray helper fails to load.

To fix this you can either 

a) include this at the top of the TbHtml.php page or
b) include the following line in your 'import' section in config/main.php:

'bootstrap.helpers.TbArray'

Hope this helps :)

Andrew

**Comment by PrajapatiRaj** [comment]
'import' => array(
        'application.models.*',
        'application.components.*',
        'bootstrap.helpers.TbHtml',
        'bootstrap.helpers.TbArray',
        'bootstrap.behaviors.TbWidget',
    ),


  see import and solve
