### ISSUE TITLE
Branch bs3: incorrect default asset path

### ISSUE THREAD

**Issue by marcovtwout** [cniska/yiistrap#223]
TbApi.php reads:

``` php
public function init()
    {
        parent::init();
        if ($this->assetsPath === null) {
            $this->assetsPath = Yii::getPathOfAlias('vendor.twbs.bootstrap.dist');
        }
    }
```

I changed this to 'bootstrap.assets' to make it work by default.

**Comment by bmsrox** [comment]
i can not to configure this extension.

**Comment by crisu83** [comment]
@bmsrox what's the exact issue?

**Comment by bmsrox** [comment]
When i try to configure this extensions show me an error CWebApplication::$bootstrap not exist.

I follow the tutorial but doesnt works. 
i am using yii 1.1.16

**Comment by crisu83** [comment]
Maybe you forgot to add the extension to your application components in
your configuration file (config/main.php by default)?

On Mon, Jan 26, 2015 at 4:13 PM, Bruno Santos <notifications@github.com>
wrote:

> When i try to configure this extensions show me an error
> CWebApplication::$bootstrap not exist.
>
> I follow the tutorial but doesnt works.
> i am using yii 1.1.16
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crisu83/yiistrap/issues/223#issuecomment-71566096>.
>



-- 
Best regards,
Christoffer Niska
Phone +1 650 575 4419
Portfolio <http://crisu83.me> · LinkedIn
<http://fi.linkedin.com/in/crisu83/> · Twitter <http://twitter.com/crisu83>
 · GitHub <http://github.com/crisu83/>
E-mail ChristofferNiska@gmail.com
